controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.25 
  min_vel_x: 0.05 
  max_vel_theta: 1.8 

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 1.0
  controller_frequency: 10

  vx_samples: 5.0
  vtheta_samples: 10.0

  pdist_scale: 0.9 
  gdist_scale: 0.6 
  occdist_scale: 0.01

  holonomic_robot: false
  
  publish_cost_grid_pc: true