map_type: costmap

obstacle_range: 3.0 
raytrace_range: 3.0 

transform_tolerance: 0.2 

robot_radius: 0.22 
inflation_radius: 0.3 
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
